In [1]:
import tensorflow as tf 
import os 

/home/saurabh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
#Change directory
os.chdir("/home/saurabh/Downloads/CatDog") 

In [3]:
#Get working directory
os.getcwd() 

'/home/saurabh/Downloads/CatDog'

In [4]:
#Define a list containing filenames 
image_paths = []

for names in os.listdir("/home/saurabh/Downloads/CatDog"):
    image_paths.append(names) 

In [5]:
#Retreiving filenames 
image_paths 

['cat.1254.jpg',
 'cat.11759.jpg',
 'dog.8546.jpg',
 'dog.10239.jpg',
 'cat.5569.jpg',
 'cat.1216.jpg',
 'dog.1418.jpg',
 'dog.567.jpg',
 'cat.11605.jpg',
 'cat.3034.jpg',
 'dog.10975.jpg',
 'cat.7478.jpg',
 'dog.7853.jpg',
 'cat.6470.jpg',
 'cat.4698.jpg',
 'cat.6358.jpg',
 'dog.4266.jpg',
 'dog.4053.jpg',
 'cat.9569.jpg',
 'dog.6765.jpg',
 'dog.5947.jpg',
 'cat.4683.jpg',
 'dog.7091.jpg',
 'dog.7868.jpg',
 'dog.6279.jpg',
 'dog.11051.jpg',
 'cat.9983.jpg',
 'dog.25.jpg',
 'cat.5920.jpg',
 'dog.6196.jpg',
 'cat.4975.jpg',
 'cat.4594.jpg',
 'cat.7887.jpg',
 'cat.9726.jpg',
 'dog.126.jpg',
 'dog.8340.jpg',
 'dog.1635.jpg',
 'cat.8510.jpg',
 'cat.11069.jpg',
 'cat.7877.jpg',
 'dog.3968.jpg',
 'cat.895.jpg',
 'cat.5291.jpg',
 'cat.1380.jpg',
 'cat.2098.jpg',
 'cat.12073.jpg',
 'dog.5062.jpg',
 'dog.5582.jpg',
 'cat.12245.jpg',
 'dog.6335.jpg',
 'dog.7050.jpg',
 'dog.273.jpg',
 'dog.11652.jpg',
 'cat.7568.jpg',
 'cat.9700.jpg',
 'dog.9077.jpg',
 'cat.844.jpg',
 'cat.11713.jpg',
 'dog.8431.

In [6]:
#No. of images 
len(image_paths) 

25000

In [7]:
#Creating tensor object for images 
data_images = tf.constant(image_paths)  

In [8]:
#Obtain the labels corresponding to each image 
labels = []

for names in os.listdir("/home/saurabh/Downloads/CatDog"):
    
    if names.startswith("c"):
        label = 0
    elif names.startswith("d"):
        label = 1
    labels.append(label)
                      

In [9]:
len(labels)

25000

In [10]:
#Creating tensor object for labels
data_labels = tf.constant(labels)   

In [11]:
#Creating train and validation dataset from tensor objects
tr_data = tf.data.Dataset.from_tensor_slices((data_images[:20000], data_labels[:20000]))  
val_data = tf.data.Dataset.from_tensor_slices((data_images[20000:], data_labels[20000:])) 

In [12]:
#Creating a generic iterator object 
iterator = tf.data.Iterator.from_structure(tr_data.output_types,tr_data.output_shapes) 
 
#Accessing the next element from the iterator 
next_element = iterator.get_next()  

In [13]:
#Initializing iterator for train and validation set
train_init_op = iterator.make_initializer(tr_data) 
val_init_op = iterator.make_initializer(val_data) 

In [14]:
with tf.Session() as sess:
    sess.run(train_init_op)
    while True:
        try:
            elem = sess.run(next_element)
            print(elem)
             
        except tf.errors.OutOfRangeError: 
            print("End of training dataset.")
            break 

(b'cat.1254.jpg', 0)
(b'cat.11759.jpg', 0)
(b'dog.8546.jpg', 1)
(b'dog.10239.jpg', 1)
(b'cat.5569.jpg', 0)
(b'cat.1216.jpg', 0)
(b'dog.1418.jpg', 1)
(b'dog.567.jpg', 1)
(b'cat.11605.jpg', 0)
(b'cat.3034.jpg', 0)
(b'dog.10975.jpg', 1)
(b'cat.7478.jpg', 0)
(b'dog.7853.jpg', 1)
(b'cat.6470.jpg', 0)
(b'cat.4698.jpg', 0)
(b'cat.6358.jpg', 0)
(b'dog.4266.jpg', 1)
(b'dog.4053.jpg', 1)
(b'cat.9569.jpg', 0)
(b'dog.6765.jpg', 1)
(b'dog.5947.jpg', 1)
(b'cat.4683.jpg', 0)
(b'dog.7091.jpg', 1)
(b'dog.7868.jpg', 1)
(b'dog.6279.jpg', 1)
(b'dog.11051.jpg', 1)
(b'cat.9983.jpg', 0)
(b'dog.25.jpg', 1)
(b'cat.5920.jpg', 0)
(b'dog.6196.jpg', 1)
(b'cat.4975.jpg', 0)
(b'cat.4594.jpg', 0)
(b'cat.7887.jpg', 0)
(b'cat.9726.jpg', 0)
(b'dog.126.jpg', 1)
(b'dog.8340.jpg', 1)
(b'dog.1635.jpg', 1)
(b'cat.8510.jpg', 0)
(b'cat.11069.jpg', 0)
(b'cat.7877.jpg', 0)
(b'dog.3968.jpg', 1)
(b'cat.895.jpg', 0)
(b'cat.5291.jpg', 0)
(b'cat.1380.jpg', 0)
(b'cat.2098.jpg', 0)
(b'cat.12073.jpg', 0)
(b'dog.5062.jpg', 1)
(b'dog.5582

(b'dog.12190.jpg', 1)
(b'cat.11524.jpg', 0)
(b'cat.2282.jpg', 0)
(b'dog.6080.jpg', 1)
(b'dog.3539.jpg', 1)
(b'cat.4913.jpg', 0)
(b'dog.8936.jpg', 1)
(b'cat.1265.jpg', 0)
(b'dog.2215.jpg', 1)
(b'dog.9693.jpg', 1)
(b'cat.11462.jpg', 0)
(b'cat.790.jpg', 0)
(b'cat.9723.jpg', 0)
(b'cat.6793.jpg', 0)
(b'dog.3818.jpg', 1)
(b'dog.10692.jpg', 1)
(b'cat.3812.jpg', 0)
(b'dog.3331.jpg', 1)
(b'cat.7593.jpg', 0)
(b'cat.11563.jpg', 0)
(b'cat.423.jpg', 0)
(b'dog.2959.jpg', 1)
(b'cat.8064.jpg', 0)
(b'cat.6563.jpg', 0)
(b'cat.7280.jpg', 0)
(b'cat.6293.jpg', 0)
(b'dog.3571.jpg', 1)
(b'dog.10695.jpg', 1)
(b'dog.7086.jpg', 1)
(b'dog.988.jpg', 1)
(b'dog.6519.jpg', 1)
(b'dog.3047.jpg', 1)
(b'cat.11601.jpg', 0)
(b'cat.4558.jpg', 0)
(b'cat.4902.jpg', 0)
(b'cat.3167.jpg', 0)
(b'dog.3690.jpg', 1)
(b'dog.8217.jpg', 1)
(b'cat.4519.jpg', 0)
(b'cat.5632.jpg', 0)
(b'dog.6253.jpg', 1)
(b'dog.7617.jpg', 1)
(b'cat.2926.jpg', 0)
(b'dog.2450.jpg', 1)
(b'cat.6668.jpg', 0)
(b'dog.11599.jpg', 1)
(b'dog.10653.jpg', 1)
(b'dog.

(b'dog.5963.jpg', 1)
(b'dog.7757.jpg', 1)
(b'dog.10415.jpg', 1)
(b'cat.2536.jpg', 0)
(b'cat.273.jpg', 0)
(b'cat.11630.jpg', 0)
(b'dog.7034.jpg', 1)
(b'dog.12293.jpg', 1)
(b'cat.5680.jpg', 0)
(b'dog.5000.jpg', 1)
(b'cat.5441.jpg', 0)
(b'cat.9529.jpg', 0)
(b'dog.4966.jpg', 1)
(b'cat.3411.jpg', 0)
(b'cat.7505.jpg', 0)
(b'cat.8747.jpg', 0)
(b'cat.10875.jpg', 0)
(b'cat.8478.jpg', 0)
(b'dog.12136.jpg', 1)
(b'dog.7690.jpg', 1)
(b'dog.3581.jpg', 1)
(b'cat.2118.jpg', 0)
(b'dog.4655.jpg', 1)
(b'dog.6953.jpg', 1)
(b'dog.8702.jpg', 1)
(b'dog.12237.jpg', 1)
(b'cat.5766.jpg', 0)
(b'dog.507.jpg', 1)
(b'dog.10644.jpg', 1)
(b'dog.6919.jpg', 1)
(b'dog.10940.jpg', 1)
(b'dog.2111.jpg', 1)
(b'cat.1077.jpg', 0)
(b'dog.11730.jpg', 1)
(b'cat.4192.jpg', 0)
(b'cat.6747.jpg', 0)
(b'cat.4631.jpg', 0)
(b'cat.2962.jpg', 0)
(b'dog.1905.jpg', 1)
(b'cat.11617.jpg', 0)
(b'cat.4001.jpg', 0)
(b'cat.1776.jpg', 0)
(b'cat.4949.jpg', 0)
(b'cat.10669.jpg', 0)
(b'cat.2542.jpg', 0)
(b'dog.53.jpg', 1)
(b'dog.8315.jpg', 1)
(b'cat

(b'dog.10221.jpg', 1)
(b'dog.3084.jpg', 1)
(b'cat.2357.jpg', 0)
(b'dog.5107.jpg', 1)
(b'cat.11335.jpg', 0)
(b'cat.11547.jpg', 0)
(b'dog.2599.jpg', 1)
(b'dog.6516.jpg', 1)
(b'cat.10104.jpg', 0)
(b'cat.2890.jpg', 0)
(b'cat.10876.jpg', 0)
(b'dog.11591.jpg', 1)
(b'cat.4546.jpg', 0)
(b'cat.716.jpg', 0)
(b'cat.9045.jpg', 0)
(b'cat.4620.jpg', 0)
(b'dog.3758.jpg', 1)
(b'cat.5594.jpg', 0)
(b'dog.369.jpg', 1)
(b'dog.7408.jpg', 1)
(b'dog.6280.jpg', 1)
(b'cat.2254.jpg', 0)
(b'dog.5688.jpg', 1)
(b'dog.1850.jpg', 1)
(b'cat.5323.jpg', 0)
(b'cat.4857.jpg', 0)
(b'cat.6616.jpg', 0)
(b'cat.7113.jpg', 0)
(b'dog.8456.jpg', 1)
(b'dog.9887.jpg', 1)
(b'dog.4192.jpg', 1)
(b'dog.4027.jpg', 1)
(b'dog.5213.jpg', 1)
(b'cat.98.jpg', 0)
(b'cat.7277.jpg', 0)
(b'cat.6729.jpg', 0)
(b'dog.2032.jpg', 1)
(b'cat.10156.jpg', 0)
(b'cat.2227.jpg', 0)
(b'dog.505.jpg', 1)
(b'cat.4339.jpg', 0)
(b'cat.2705.jpg', 0)
(b'dog.4259.jpg', 1)
(b'dog.9850.jpg', 1)
(b'dog.4940.jpg', 1)
(b'dog.2098.jpg', 1)
(b'cat.2006.jpg', 0)
(b'cat.1203

(b'cat.2215.jpg', 0)
(b'dog.12184.jpg', 1)
(b'dog.4993.jpg', 1)
(b'dog.2788.jpg', 1)
(b'dog.1253.jpg', 1)
(b'cat.1721.jpg', 0)
(b'cat.3417.jpg', 0)
(b'cat.3483.jpg', 0)
(b'dog.3815.jpg', 1)
(b'dog.2596.jpg', 1)
(b'cat.5230.jpg', 0)
(b'dog.7881.jpg', 1)
(b'dog.6768.jpg', 1)
(b'cat.11337.jpg', 0)
(b'dog.8927.jpg', 1)
(b'cat.664.jpg', 0)
(b'cat.9159.jpg', 0)
(b'dog.12494.jpg', 1)
(b'cat.5591.jpg', 0)
(b'cat.488.jpg', 0)
(b'cat.10.jpg', 0)
(b'dog.6430.jpg', 1)
(b'cat.6715.jpg', 0)
(b'dog.11227.jpg', 1)
(b'cat.11333.jpg', 0)
(b'cat.358.jpg', 0)
(b'dog.5337.jpg', 1)
(b'cat.4426.jpg', 0)
(b'cat.5062.jpg', 0)
(b'cat.9573.jpg', 0)
(b'dog.264.jpg', 1)
(b'dog.9669.jpg', 1)
(b'cat.3007.jpg', 0)
(b'cat.2562.jpg', 0)
(b'dog.8687.jpg', 1)
(b'dog.4763.jpg', 1)
(b'cat.6641.jpg', 0)
(b'cat.6009.jpg', 0)
(b'cat.8011.jpg', 0)
(b'dog.7438.jpg', 1)
(b'cat.9176.jpg', 0)
(b'cat.8124.jpg', 0)
(b'cat.3268.jpg', 0)
(b'dog.1679.jpg', 1)
(b'cat.12275.jpg', 0)
(b'dog.11939.jpg', 1)
(b'dog.5779.jpg', 1)
(b'dog.11791

(b'dog.3119.jpg', 1)
(b'dog.4735.jpg', 1)
(b'dog.9092.jpg', 1)
(b'dog.2514.jpg', 1)
(b'cat.402.jpg', 0)
(b'cat.2964.jpg', 0)
(b'cat.6559.jpg', 0)
(b'dog.6183.jpg', 1)
(b'dog.2634.jpg', 1)
(b'dog.11731.jpg', 1)
(b'dog.2825.jpg', 1)
(b'cat.12418.jpg', 0)
(b'cat.8211.jpg', 0)
(b'dog.3840.jpg', 1)
(b'cat.3593.jpg', 0)
(b'dog.3786.jpg', 1)
(b'cat.7929.jpg', 0)
(b'dog.3018.jpg', 1)
(b'dog.11623.jpg', 1)
(b'cat.10146.jpg', 0)
(b'cat.8109.jpg', 0)
(b'cat.1627.jpg', 0)
(b'dog.6545.jpg', 1)
(b'cat.7607.jpg', 0)
(b'dog.11122.jpg', 1)
(b'cat.6820.jpg', 0)
(b'dog.10661.jpg', 1)
(b'cat.12130.jpg', 0)
(b'cat.11139.jpg', 0)
(b'dog.4498.jpg', 1)
(b'dog.8748.jpg', 1)
(b'cat.9395.jpg', 0)
(b'dog.4915.jpg', 1)
(b'cat.1033.jpg', 0)
(b'cat.7702.jpg', 0)
(b'cat.9646.jpg', 0)
(b'cat.2982.jpg', 0)
(b'dog.10199.jpg', 1)
(b'cat.12168.jpg', 0)
(b'dog.11867.jpg', 1)
(b'cat.2334.jpg', 0)
(b'dog.2705.jpg', 1)
(b'dog.11787.jpg', 1)
(b'dog.218.jpg', 1)
(b'dog.3664.jpg', 1)
(b'cat.12436.jpg', 0)
(b'dog.11098.jpg', 1)
(

(b'dog.3648.jpg', 1)
(b'dog.9293.jpg', 1)
(b'dog.9006.jpg', 1)
(b'dog.5025.jpg', 1)
(b'cat.8705.jpg', 0)
(b'dog.10353.jpg', 1)
(b'dog.4517.jpg', 1)
(b'dog.5949.jpg', 1)
(b'cat.4307.jpg', 0)
(b'dog.2364.jpg', 1)
(b'cat.6844.jpg', 0)
(b'dog.12149.jpg', 1)
(b'cat.11404.jpg', 0)
(b'cat.4264.jpg', 0)
(b'dog.116.jpg', 1)
(b'dog.4644.jpg', 1)
(b'cat.795.jpg', 0)
(b'cat.7766.jpg', 0)
(b'cat.4983.jpg', 0)
(b'dog.10529.jpg', 1)
(b'cat.12105.jpg', 0)
(b'cat.8539.jpg', 0)
(b'cat.5557.jpg', 0)
(b'dog.6906.jpg', 1)
(b'dog.5826.jpg', 1)
(b'dog.8626.jpg', 1)
(b'cat.3055.jpg', 0)
(b'cat.7756.jpg', 0)
(b'cat.6138.jpg', 0)
(b'dog.2509.jpg', 1)
(b'cat.6675.jpg', 0)
(b'dog.11085.jpg', 1)
(b'dog.8301.jpg', 1)
(b'dog.2608.jpg', 1)
(b'cat.3533.jpg', 0)
(b'dog.4089.jpg', 1)
(b'cat.751.jpg', 0)
(b'cat.798.jpg', 0)
(b'dog.9861.jpg', 1)
(b'dog.9924.jpg', 1)
(b'cat.8153.jpg', 0)
(b'cat.12005.jpg', 0)
(b'cat.3115.jpg', 0)
(b'dog.6677.jpg', 1)
(b'dog.6597.jpg', 1)
(b'dog.4574.jpg', 1)
(b'dog.6419.jpg', 1)
(b'cat.434

(b'dog.11294.jpg', 1)
(b'cat.2983.jpg', 0)
(b'dog.2917.jpg', 1)
(b'cat.8995.jpg', 0)
(b'dog.732.jpg', 1)
(b'cat.12045.jpg', 0)
(b'dog.6772.jpg', 1)
(b'dog.7118.jpg', 1)
(b'dog.1812.jpg', 1)
(b'cat.2503.jpg', 0)
(b'dog.12492.jpg', 1)
(b'cat.3518.jpg', 0)
(b'dog.5249.jpg', 1)
(b'dog.11224.jpg', 1)
(b'dog.6064.jpg', 1)
(b'dog.11761.jpg', 1)
(b'cat.8739.jpg', 0)
(b'cat.5055.jpg', 0)
(b'dog.8516.jpg', 1)
(b'cat.9106.jpg', 0)
(b'cat.933.jpg', 0)
(b'cat.12224.jpg', 0)
(b'cat.562.jpg', 0)
(b'cat.6516.jpg', 0)
(b'dog.6672.jpg', 1)
(b'cat.7985.jpg', 0)
(b'dog.10456.jpg', 1)
(b'cat.3561.jpg', 0)
(b'dog.8265.jpg', 1)
(b'dog.7406.jpg', 1)
(b'dog.7667.jpg', 1)
(b'cat.5341.jpg', 0)
(b'cat.1564.jpg', 0)
(b'cat.1618.jpg', 0)
(b'dog.10439.jpg', 1)
(b'dog.2845.jpg', 1)
(b'dog.743.jpg', 1)
(b'cat.1648.jpg', 0)
(b'dog.3943.jpg', 1)
(b'dog.11391.jpg', 1)
(b'cat.9407.jpg', 0)
(b'cat.5354.jpg', 0)
(b'cat.3554.jpg', 0)
(b'dog.9688.jpg', 1)
(b'cat.9767.jpg', 0)
(b'dog.1110.jpg', 1)
(b'dog.1829.jpg', 1)
(b'dog.4

(b'dog.10754.jpg', 1)
(b'cat.457.jpg', 0)
(b'dog.10171.jpg', 1)
(b'cat.12310.jpg', 0)
(b'dog.4154.jpg', 1)
(b'cat.1592.jpg', 0)
(b'cat.4077.jpg', 0)
(b'cat.878.jpg', 0)
(b'cat.6689.jpg', 0)
(b'cat.7851.jpg', 0)
(b'dog.8378.jpg', 1)
(b'dog.2919.jpg', 1)
(b'dog.1460.jpg', 1)
(b'dog.8218.jpg', 1)
(b'cat.11112.jpg', 0)
(b'dog.9623.jpg', 1)
(b'cat.3062.jpg', 0)
(b'dog.10084.jpg', 1)
(b'dog.10816.jpg', 1)
(b'cat.11643.jpg', 0)
(b'dog.5566.jpg', 1)
(b'cat.2049.jpg', 0)
(b'dog.9182.jpg', 1)
(b'cat.2807.jpg', 0)
(b'dog.1881.jpg', 1)
(b'cat.6923.jpg', 0)
(b'dog.4974.jpg', 1)
(b'cat.6123.jpg', 0)
(b'cat.9666.jpg', 0)
(b'dog.3695.jpg', 1)
(b'cat.2660.jpg', 0)
(b'dog.10537.jpg', 1)
(b'dog.2686.jpg', 1)
(b'cat.150.jpg', 0)
(b'dog.3196.jpg', 1)
(b'dog.10670.jpg', 1)
(b'cat.10027.jpg', 0)
(b'dog.1067.jpg', 1)
(b'cat.10436.jpg', 0)
(b'cat.7056.jpg', 0)
(b'dog.10492.jpg', 1)
(b'cat.6243.jpg', 0)
(b'dog.596.jpg', 1)
(b'cat.6583.jpg', 0)
(b'dog.11854.jpg', 1)
(b'dog.4483.jpg', 1)
(b'dog.7148.jpg', 1)
(b'c

(b'cat.12291.jpg', 0)
(b'cat.4959.jpg', 0)
(b'dog.9851.jpg', 1)
(b'cat.7438.jpg', 0)
(b'dog.10741.jpg', 1)
(b'dog.7302.jpg', 1)
(b'cat.6350.jpg', 0)
(b'cat.10432.jpg', 0)
(b'cat.598.jpg', 0)
(b'cat.10781.jpg', 0)
(b'cat.1249.jpg', 0)
(b'cat.7587.jpg', 0)
(b'dog.1032.jpg', 1)
(b'dog.8505.jpg', 1)
(b'dog.395.jpg', 1)
(b'dog.2060.jpg', 1)
(b'dog.1999.jpg', 1)
(b'cat.7314.jpg', 0)
(b'dog.10689.jpg', 1)
(b'cat.579.jpg', 0)
(b'cat.2674.jpg', 0)
(b'dog.10648.jpg', 1)
(b'cat.6185.jpg', 0)
(b'cat.4241.jpg', 0)
(b'dog.11752.jpg', 1)
(b'cat.4821.jpg', 0)
(b'cat.6605.jpg', 0)
(b'dog.8581.jpg', 1)
(b'dog.4729.jpg', 1)
(b'dog.4270.jpg', 1)
(b'cat.9311.jpg', 0)
(b'dog.792.jpg', 1)
(b'cat.339.jpg', 0)
(b'cat.5979.jpg', 0)
(b'cat.7166.jpg', 0)
(b'cat.1659.jpg', 0)
(b'dog.1634.jpg', 1)
(b'dog.4015.jpg', 1)
(b'dog.6454.jpg', 1)
(b'dog.10901.jpg', 1)
(b'cat.2602.jpg', 0)
(b'cat.7421.jpg', 0)
(b'cat.7316.jpg', 0)
(b'cat.8744.jpg', 0)
(b'cat.11316.jpg', 0)
(b'dog.9025.jpg', 1)
(b'dog.9147.jpg', 1)
(b'dog.10

(b'cat.10471.jpg', 0)
(b'dog.570.jpg', 1)
(b'cat.4138.jpg', 0)
(b'cat.3295.jpg', 0)
(b'cat.9631.jpg', 0)
(b'cat.793.jpg', 0)
(b'dog.6368.jpg', 1)
(b'dog.5347.jpg', 1)
(b'cat.89.jpg', 0)
(b'cat.10766.jpg', 0)
(b'cat.1545.jpg', 0)
(b'cat.7731.jpg', 0)
(b'cat.6802.jpg', 0)
(b'dog.7340.jpg', 1)
(b'dog.9798.jpg', 1)
(b'dog.2613.jpg', 1)
(b'dog.6728.jpg', 1)
(b'cat.12278.jpg', 0)
(b'cat.1712.jpg', 0)
(b'dog.697.jpg', 1)
(b'cat.4397.jpg', 0)
(b'cat.890.jpg', 0)
(b'dog.2246.jpg', 1)
(b'cat.8980.jpg', 0)
(b'cat.10319.jpg', 0)
(b'cat.10970.jpg', 0)
(b'dog.1701.jpg', 1)
(b'cat.11608.jpg', 0)
(b'dog.5885.jpg', 1)
(b'dog.1989.jpg', 1)
(b'cat.6162.jpg', 0)
(b'cat.593.jpg', 0)
(b'cat.10464.jpg', 0)
(b'cat.7196.jpg', 0)
(b'cat.6621.jpg', 0)
(b'cat.3864.jpg', 0)
(b'dog.3958.jpg', 1)
(b'cat.3317.jpg', 0)
(b'cat.3919.jpg', 0)
(b'dog.5910.jpg', 1)
(b'cat.9585.jpg', 0)
(b'cat.5531.jpg', 0)
(b'dog.3572.jpg', 1)
(b'cat.8485.jpg', 0)
(b'cat.11240.jpg', 0)
(b'cat.7349.jpg', 0)
(b'cat.5028.jpg', 0)
(b'dog.11521

(b'cat.11543.jpg', 0)
(b'cat.12306.jpg', 0)
(b'cat.941.jpg', 0)
(b'dog.3229.jpg', 1)
(b'cat.4438.jpg', 0)
(b'cat.3903.jpg', 0)
(b'cat.8043.jpg', 0)
(b'dog.9452.jpg', 1)
(b'dog.4902.jpg', 1)
(b'dog.3509.jpg', 1)
(b'dog.5781.jpg', 1)
(b'cat.12361.jpg', 0)
(b'dog.9811.jpg', 1)
(b'dog.5092.jpg', 1)
(b'dog.11750.jpg', 1)
(b'dog.613.jpg', 1)
(b'cat.11538.jpg', 0)
(b'dog.9379.jpg', 1)
(b'cat.3880.jpg', 0)
(b'cat.2782.jpg', 0)
(b'dog.4460.jpg', 1)
(b'cat.11186.jpg', 0)
(b'cat.10290.jpg', 0)
(b'cat.4940.jpg', 0)
(b'cat.9218.jpg', 0)
(b'cat.12273.jpg', 0)
(b'cat.6377.jpg', 0)
(b'cat.4060.jpg', 0)
(b'cat.8458.jpg', 0)
(b'dog.58.jpg', 1)
(b'cat.4977.jpg', 0)
(b'cat.3102.jpg', 0)
(b'dog.11778.jpg', 1)
(b'dog.5932.jpg', 1)
(b'cat.10549.jpg', 0)
(b'cat.6965.jpg', 0)
(b'cat.3913.jpg', 0)
(b'cat.2749.jpg', 0)
(b'dog.2946.jpg', 1)
(b'cat.4805.jpg', 0)
(b'dog.2768.jpg', 1)
(b'cat.6326.jpg', 0)
(b'cat.11866.jpg', 0)
(b'dog.1088.jpg', 1)
(b'dog.1411.jpg', 1)
(b'dog.3964.jpg', 1)
(b'dog.531.jpg', 1)
(b'cat.

(b'cat.1128.jpg', 0)
(b'cat.1793.jpg', 0)
(b'cat.6816.jpg', 0)
(b'cat.2779.jpg', 0)
(b'cat.5384.jpg', 0)
(b'cat.4273.jpg', 0)
(b'cat.4129.jpg', 0)
(b'dog.11425.jpg', 1)
(b'dog.1144.jpg', 1)
(b'cat.1995.jpg', 0)
(b'cat.117.jpg', 0)
(b'cat.4029.jpg', 0)
(b'dog.10800.jpg', 1)
(b'cat.4765.jpg', 0)
(b'cat.7528.jpg', 0)
(b'cat.3259.jpg', 0)
(b'dog.9165.jpg', 1)
(b'dog.3423.jpg', 1)
(b'dog.10914.jpg', 1)
(b'dog.3227.jpg', 1)
(b'cat.5746.jpg', 0)
(b'cat.3716.jpg', 0)
(b'cat.2621.jpg', 0)
(b'cat.627.jpg', 0)
(b'dog.5314.jpg', 1)
(b'cat.8423.jpg', 0)
(b'cat.10607.jpg', 0)
(b'cat.7968.jpg', 0)
(b'cat.8393.jpg', 0)
(b'dog.1770.jpg', 1)
(b'cat.9129.jpg', 0)
(b'dog.4627.jpg', 1)
(b'dog.3102.jpg', 1)
(b'cat.1260.jpg', 0)
(b'dog.7276.jpg', 1)
(b'cat.11208.jpg', 0)
(b'cat.12083.jpg', 0)
(b'dog.4241.jpg', 1)
(b'dog.4313.jpg', 1)
(b'cat.7858.jpg', 0)
(b'dog.2238.jpg', 1)
(b'dog.936.jpg', 1)
(b'dog.2458.jpg', 1)
(b'cat.2221.jpg', 0)
(b'dog.884.jpg', 1)
(b'cat.6867.jpg', 0)
(b'dog.586.jpg', 1)
(b'cat.12157

(b'dog.4433.jpg', 1)
(b'cat.4866.jpg', 0)
(b'dog.7222.jpg', 1)
(b'cat.7797.jpg', 0)
(b'dog.10107.jpg', 1)
(b'cat.11045.jpg', 0)
(b'cat.8663.jpg', 0)
(b'dog.12144.jpg', 1)
(b'dog.8275.jpg', 1)
(b'cat.3130.jpg', 0)
(b'cat.1031.jpg', 0)
(b'cat.1805.jpg', 0)
(b'dog.6878.jpg', 1)
(b'dog.2633.jpg', 1)
(b'cat.12334.jpg', 0)
(b'cat.4369.jpg', 0)
(b'dog.2206.jpg', 1)
(b'cat.6789.jpg', 0)
(b'cat.12122.jpg', 0)
(b'dog.7759.jpg', 1)
(b'cat.3412.jpg', 0)
(b'dog.1614.jpg', 1)
(b'dog.7163.jpg', 1)
(b'cat.4728.jpg', 0)
(b'dog.6808.jpg', 1)
(b'dog.171.jpg', 1)
(b'dog.8976.jpg', 1)
(b'cat.6939.jpg', 0)
(b'dog.7065.jpg', 1)
(b'dog.4811.jpg', 1)
(b'cat.6817.jpg', 0)
(b'cat.1356.jpg', 0)
(b'cat.9965.jpg', 0)
(b'dog.7919.jpg', 1)
(b'cat.3872.jpg', 0)
(b'cat.6853.jpg', 0)
(b'cat.378.jpg', 0)
(b'cat.11562.jpg', 0)
(b'dog.8164.jpg', 1)
(b'dog.4481.jpg', 1)
(b'dog.5777.jpg', 1)
(b'dog.4823.jpg', 1)
(b'dog.4619.jpg', 1)
(b'cat.6435.jpg', 0)
(b'cat.12430.jpg', 0)
(b'dog.1205.jpg', 1)
(b'dog.6126.jpg', 1)
(b'cat.8

(b'dog.9321.jpg', 1)
(b'dog.3150.jpg', 1)
(b'cat.4187.jpg', 0)
(b'cat.811.jpg', 0)
(b'dog.7619.jpg', 1)
(b'cat.1273.jpg', 0)
(b'cat.1585.jpg', 0)
(b'dog.699.jpg', 1)
(b'cat.1910.jpg', 0)
(b'dog.3755.jpg', 1)
(b'cat.7198.jpg', 0)
(b'cat.11364.jpg', 0)
(b'cat.10925.jpg', 0)
(b'cat.831.jpg', 0)
(b'cat.12117.jpg', 0)
(b'cat.5116.jpg', 0)
(b'dog.8334.jpg', 1)
(b'cat.6169.jpg', 0)
(b'cat.12043.jpg', 0)
(b'dog.1602.jpg', 1)
(b'cat.2491.jpg', 0)
(b'cat.1926.jpg', 0)
(b'dog.1072.jpg', 1)
(b'dog.6038.jpg', 1)
(b'cat.5067.jpg', 0)
(b'dog.11642.jpg', 1)
(b'dog.8352.jpg', 1)
(b'dog.3789.jpg', 1)
(b'cat.1295.jpg', 0)
(b'cat.3814.jpg', 0)
(b'dog.5131.jpg', 1)
(b'dog.9453.jpg', 1)
(b'dog.12445.jpg', 1)
(b'dog.840.jpg', 1)
(b'dog.2806.jpg', 1)
(b'cat.2405.jpg', 0)
(b'dog.8582.jpg', 1)
(b'cat.90.jpg', 0)
(b'dog.2549.jpg', 1)
(b'dog.16.jpg', 1)
(b'cat.3418.jpg', 0)
(b'cat.2847.jpg', 0)
(b'cat.7069.jpg', 0)
(b'cat.9088.jpg', 0)
(b'dog.10103.jpg', 1)
(b'cat.2419.jpg', 0)
(b'cat.9693.jpg', 0)
(b'cat.2781.jp

(b'cat.7160.jpg', 0)
(b'cat.11007.jpg', 0)
(b'dog.3012.jpg', 1)
(b'dog.5945.jpg', 1)
(b'cat.1838.jpg', 0)
(b'dog.3717.jpg', 1)
(b'cat.9328.jpg', 0)
(b'cat.9951.jpg', 0)
(b'dog.10864.jpg', 1)
(b'cat.1370.jpg', 0)
(b'cat.6413.jpg', 0)
(b'cat.1316.jpg', 0)
(b'cat.10459.jpg', 0)
(b'dog.7779.jpg', 1)
(b'cat.7987.jpg', 0)
(b'dog.9916.jpg', 1)
(b'dog.1331.jpg', 1)
(b'cat.1885.jpg', 0)
(b'cat.10908.jpg', 0)
(b'dog.8925.jpg', 1)
(b'cat.7422.jpg', 0)
(b'dog.8999.jpg', 1)
(b'dog.6237.jpg', 1)
(b'cat.4682.jpg', 0)
(b'cat.9352.jpg', 0)
(b'dog.8484.jpg', 1)
(b'dog.1028.jpg', 1)
(b'cat.4345.jpg', 0)
(b'cat.5692.jpg', 0)
(b'cat.11008.jpg', 0)
(b'cat.8161.jpg', 0)
(b'cat.5792.jpg', 0)
(b'dog.5490.jpg', 1)
(b'cat.10348.jpg', 0)
(b'cat.1956.jpg', 0)
(b'dog.7498.jpg', 1)
(b'cat.10107.jpg', 0)
(b'dog.1366.jpg', 1)
(b'dog.6640.jpg', 1)
(b'cat.7678.jpg', 0)
(b'cat.112.jpg', 0)
(b'cat.8418.jpg', 0)
(b'dog.7568.jpg', 1)
(b'cat.1528.jpg', 0)
(b'cat.7089.jpg', 0)
(b'dog.10767.jpg', 1)
(b'dog.1452.jpg', 1)
(b'dog

(b'cat.11399.jpg', 0)
(b'dog.4970.jpg', 1)
(b'cat.9280.jpg', 0)
(b'dog.3699.jpg', 1)
(b'cat.5754.jpg', 0)
(b'dog.10977.jpg', 1)
(b'cat.1222.jpg', 0)
(b'dog.6720.jpg', 1)
(b'cat.10687.jpg', 0)
(b'cat.1530.jpg', 0)
(b'dog.8550.jpg', 1)
(b'cat.2020.jpg', 0)
(b'cat.6635.jpg', 0)
(b'dog.5284.jpg', 1)
(b'dog.9864.jpg', 1)
(b'cat.596.jpg', 0)
(b'dog.5345.jpg', 1)
(b'cat.7979.jpg', 0)
(b'cat.1030.jpg', 0)
(b'cat.4097.jpg', 0)
(b'cat.6407.jpg', 0)
(b'dog.700.jpg', 1)
(b'dog.7383.jpg', 1)
(b'dog.1699.jpg', 1)
(b'dog.9799.jpg', 1)
(b'dog.4060.jpg', 1)
(b'cat.2239.jpg', 0)
(b'dog.2284.jpg', 1)
(b'cat.3776.jpg', 0)
(b'cat.7262.jpg', 0)
(b'dog.2601.jpg', 1)
(b'dog.3089.jpg', 1)
(b'cat.6707.jpg', 0)
(b'cat.10858.jpg', 0)
(b'dog.11260.jpg', 1)
(b'cat.11925.jpg', 0)
(b'dog.5029.jpg', 1)
(b'dog.4689.jpg', 1)
(b'cat.6575.jpg', 0)
(b'dog.8443.jpg', 1)
(b'cat.11121.jpg', 0)
(b'dog.4051.jpg', 1)
(b'cat.11444.jpg', 0)
(b'dog.1710.jpg', 1)
(b'cat.2018.jpg', 0)
(b'dog.3959.jpg', 1)
(b'cat.6316.jpg', 0)
(b'dog.

(b'cat.1596.jpg', 0)
(b'dog.3085.jpg', 1)
(b'dog.1228.jpg', 1)
(b'dog.843.jpg', 1)
(b'cat.8420.jpg', 0)
(b'cat.5801.jpg', 0)
(b'cat.4366.jpg', 0)
(b'dog.6246.jpg', 1)
(b'dog.2079.jpg', 1)
(b'cat.1420.jpg', 0)
(b'cat.9112.jpg', 0)
(b'dog.8182.jpg', 1)
(b'cat.10733.jpg', 0)
(b'dog.8534.jpg', 1)
(b'cat.3897.jpg', 0)
(b'cat.3253.jpg', 0)
(b'cat.2288.jpg', 0)
(b'dog.3662.jpg', 1)
(b'cat.4578.jpg', 0)
(b'dog.3750.jpg', 1)
(b'cat.237.jpg', 0)
(b'dog.4219.jpg', 1)
(b'cat.590.jpg', 0)
(b'cat.5173.jpg', 0)
(b'cat.2647.jpg', 0)
(b'cat.4365.jpg', 0)
(b'dog.9132.jpg', 1)
(b'dog.6929.jpg', 1)
(b'cat.9403.jpg', 0)
(b'dog.10290.jpg', 1)
(b'dog.9753.jpg', 1)
(b'cat.10604.jpg', 0)
(b'dog.1356.jpg', 1)
(b'cat.11863.jpg', 0)
(b'dog.1966.jpg', 1)
(b'dog.559.jpg', 1)
(b'cat.740.jpg', 0)
(b'cat.476.jpg', 0)
(b'dog.8553.jpg', 1)
(b'dog.10232.jpg', 1)
(b'cat.11120.jpg', 0)
(b'cat.8910.jpg', 0)
(b'cat.9084.jpg', 0)
(b'cat.553.jpg', 0)
(b'cat.4738.jpg', 0)
(b'cat.4935.jpg', 0)
(b'dog.6445.jpg', 1)
(b'dog.9120.jp

In [15]:
#Defining an input parser
def parse_function(filename, label):
    image_string = tf.read_file(filename)
    

    image = tf.image.decode_jpeg(image_string, channels=3)
      
    # Converting to float values 
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.image.resize_images(image, [64, 64]) 
    return image, label 

In [16]:
tr_data = tr_data.map(parse_function) 

In [17]:
val_data = val_data.map(parse_function) 

In [19]:
#Defining augmentation functions 
def img_augmentation(image, label):
    
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_contrast(image, 0.2, 1.8, seed=1) 
    image = tf.image.random_brightness(image, max_delta=32.0 / 255.0)
    image = tf.image.random_saturation(image, lower=0.5, upper=1.5)
    image = tf.image.random_hue(image, max_delta=32.0 / 255) 
   
    # Make sure the image is still in [0, 1]
    image = tf.clip_by_value(image, 0.0, 1.0)

    return image, label  

In [20]:
#Augmentated Data 
Aug_data = tr_data.map(img_augmentation, num_parallel_calls=4)   

In [21]:
#Concatenating augmentated data with the trainset 
train_data = tr_data.concatenate(Aug_data) 

In [22]:
#Shuffle the trainset
train_data = train_data.shuffle(len(image_paths)) 

In [23]:
#Batch size 
train_data = train_data.batch(16) 
train_data = train_data.prefetch(1)  
val_data = val_data.batch(16) 
val_data = val_data.prefetch(1) 

In [24]:
iterator = train_data.make_initializable_iterator() 
 
#Accessing the next element from the iterator 
images, labels = iterator.get_next()   

In [25]:
#Image shape
images 

<tf.Tensor 'IteratorGetNext_1:0' shape=(?, 64, 64, 3) dtype=float32>

In [26]:
#Labels shape 
labels 

<tf.Tensor 'IteratorGetNext_1:1' shape=(?,) dtype=int32>

In [27]:
#Train and validation set iterator initialization 
training_init_op = iterator.make_initializer(train_data)   
valid_init_op = iterator.make_initializer(val_data) 

In [120]:
#Retreiving image arrays after parsing 
with tf.Session() as sess:
    sess.run(training_init_op) 
    for i in range(5):
        elem = sess.run(images) 
        print(elem)

[[[[8.23529482e-01 6.03921592e-01 3.09803933e-01]
   [8.04902017e-01 5.87500036e-01 2.84803927e-01]
   [7.76470661e-01 5.76470613e-01 2.66666681e-01]
   ...
   [9.57843184e-01 8.04902017e-01 5.81372559e-01]
   [9.65686321e-01 8.12745154e-01 5.89215696e-01]
   [9.33333397e-01 7.80392230e-01 5.56862772e-01]]

  [[8.14215779e-01 5.94607890e-01 2.95588255e-01]
   [7.98039258e-01 5.80637276e-01 2.77941167e-01]
   [7.67156959e-01 5.65686345e-01 2.60294110e-01]
   ...
   [9.53615248e-01 8.05576026e-01 5.86948514e-01]
   [9.39154446e-01 7.91115284e-01 5.72487772e-01]
   [9.54411805e-01 8.06372643e-01 5.87745130e-01]]

  [[8.07843208e-01 5.89215696e-01 2.84313738e-01]
   [7.87254930e-01 5.70649564e-01 2.65563726e-01]
   [7.51838326e-01 5.47916710e-01 2.51348048e-01]
   ...
   [9.77328479e-01 8.40073586e-01 6.28308833e-01]
   [9.29534376e-01 7.92279482e-01 5.80514729e-01]
   [9.57904458e-01 8.20649624e-01 6.08884811e-01]]

  ...

  [[9.19117689e-01 8.68137300e-01 8.05392206e-01]
   [9.28462088e-

In [33]:
#Stacking layers as per VGG first block 
conv1 = tf.layers.conv2d(images, filters= 64, kernel_size= (3,3), strides=(1,1), activation=tf.nn.relu, kernel_initializer= tf.truncated_normal_initializer)  
conv2 = tf.layers.conv2d(conv1, filters= 64, kernel_size= (3,3), strides=(1,1), activation=tf.nn.relu)   
max1 = tf.layers.max_pooling2d(conv2, pool_size=(2,2), strides = (2,2)) 
flatten = tf.layers.flatten(max1) 

#Adding fully connected layers 
fc1 = tf.layers.dense(flatten, 512, activation= tf.nn.sigmoid, kernel_initializer=tf.truncated_normal_initializer) 
fc2 = tf.layers.dense(fc1, 2)    


In [35]:
loss = tf.reduce_sum(tf.nn.sparse_softmax_cross_entropy_with_logits(labels= labels, logits=fc2)) 
optimizer = tf.train.AdamOptimizer().minimize(loss)
# get accuracy
prediction = tf.argmax(fc2, 1, output_type=tf.int32)
equality = tf.equal(prediction, labels) 
accuracy = tf.reduce_mean(tf.cast(equality, tf.float32))    
init_op = tf.global_variables_initializer()   

In [36]:
epochs = 100
with tf.Session() as sess:
    sess.run(init_op)
    sess.run(training_init_op)
    for i in range(epochs):
         
        l, _, acc = sess.run([loss, optimizer, accuracy])
        if i % 5== 0:
            print("Epoch: {}, loss: {:.3f}, training accuracy: {:.2f}%".format(i, l, acc * 100)) 
            
    valid_iters= 200
    sess.run(valid_init_op)
    avg_acc = 0
    for i in range(valid_iters):
        acc = sess.run([accuracy]) 
        avg_acc += acc[0] 
    print("Average validation set accuracy over {} iterations is {:.2f}%".format(valid_iters, (avg_acc / valid_iters) * 100))

            
            
    

Epoch: 0, loss: 16.808, training accuracy: 50.00%
Epoch: 5, loss: 11.941, training accuracy: 56.25%
Epoch: 10, loss: 13.827, training accuracy: 25.00%
Epoch: 15, loss: 11.482, training accuracy: 50.00%
Epoch: 20, loss: 12.347, training accuracy: 56.25%
Epoch: 25, loss: 10.377, training accuracy: 62.50%
Epoch: 30, loss: 11.077, training accuracy: 56.25%
Epoch: 35, loss: 13.919, training accuracy: 43.75%
Epoch: 40, loss: 12.240, training accuracy: 37.50%
Epoch: 45, loss: 9.478, training accuracy: 87.50%
Epoch: 50, loss: 10.867, training accuracy: 43.75%
Epoch: 55, loss: 10.344, training accuracy: 62.50%
Epoch: 60, loss: 11.288, training accuracy: 56.25%
Epoch: 65, loss: 11.913, training accuracy: 50.00%
Epoch: 70, loss: 12.611, training accuracy: 31.25%
Epoch: 75, loss: 11.806, training accuracy: 37.50%
Epoch: 80, loss: 9.933, training accuracy: 68.75%
Epoch: 85, loss: 13.615, training accuracy: 31.25%
Epoch: 90, loss: 11.456, training accuracy: 37.50%
Epoch: 95, loss: 10.736, training a